### ISSUE TITLE
Question about comments export

### ISSUE THREAD

**Issue by adrienne** [danlmarmot/livejournal-export#1]
Your README says "Your LJ friends comments to your posts" will be exported. Does it also export anonymous and/or non-friend comments?

**Comment by danlmarmot** [comment]
Yes, it exports both anonymous and non-friend comments.  It also will export comments from deleted users.

A warning--the script is decent with downloading content (posts, comments, userpics), which was its main goal.   It caches the downloaded content locally, and then creates the Markdown export.  That Markdown export is intended to be consumed by Pelican to generate a static site, and for the most part works, although there are some rough bits here and there.
